[project]
name = "webhook-delivery-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jacson Rodrigues", email = "github.obsessive123@passmail.net" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.0",
    "celery[redis]>=5.6.3",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
]

[project.scripts]
webhook-delivery-service = "webhook_delivery_service:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
target-version = "py314"
line-length = 70
exclude = [
  "alembic/"
]

[tool.ruff.lint]
select = [
  "E",
  "F"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
python_version = "3.14"
strict = true

[[tool.mypy.overrides]]
module = ["celery","celery.*"]
ignore_missing_imports = true
