"""add indexes

Revision ID: 278dc52dcc3a
Revises: 9d9b7f9d1711
Create Date: 2026-08-10 17:16:25.000809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278dc52dcc3a'
down_revision: Union[str, Sequence[str], None] = '9d9b7f9d1711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_deliveries_event_id', 'deliveries', ['event_id'], unique=False)
    op.create_index('ix_deliveries_webhook_id', 'deliveries', ['webhook_id'], unique=False)
    op.create_index('ix_events_type', 'events', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_type', table_name='events')
    op.drop_index('ix_deliveries_webhook_id', table_name='deliveries')
    op.drop_index('ix_deliveries_event_id', table_name='deliveries')
    # ### end Alembic commands ###
