"""rename event data to payload

Revision ID: 56b81dc56b65
Revises: 278dc52dcc3a
Create Date: 2026-08-11 23:21:35.993587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56b81dc56b65'
down_revision: Union[str, Sequence[str], None] = '278dc52dcc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "data",
        new_column_name="payload"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "payload",
        new_column_name="data"
    )
    # ### end Alembic commands ###
